name: CI

on: [push]

concurrency:
    group: ${{ github.ref }}-test
    cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    container: rust:1.76
    steps:
    - uses: actions/checkout@v3
    - run: cargo build
      working-directory: ./exercises
    - run: cargo test
      working-directory: ./exercises